export const objectSkills = [
    {
        id: 1,
        title: "skillsFrameworks.titleFramework",
        tecnology: "HTML/CSS",
        text: ["Tailwind CSS", "Material ui", "Styled Components/emotion"],
    },
    {
        id: 2,
        title: "skillsFrameworks.titleKnowledge",
        tecnology: "Js",
        text: [
            "skillsFrameworks.textHtml1",
            "skillsFrameworks.textHtml2",
            "skillsFrameworks.textHtml3",
            "skillsFrameworks.textHtml4",
            "skillsFrameworks.textHtml5",
            "skillsFrameworks.textHtml6",
            "skillsFrameworks.textHtml7",
            "skillsFrameworks.textHtml8",
        ],
    },
    {
        id: 3,
        title: "skillsFrameworks.titleFramework",
        tecnology: "React",
        text: [
            "React Redux",
            "React Redux Toolkit",
            "React Router",
            "Emailjs",
            "I18next",
        ],
    },
    {
        id: 4,
        title: "skillsFrameworks.titleKnowledge",
        tecnology: "Git",
        text: [
            "skillsFrameworks.textGit1",
            "skillsFrameworks.textGit2",
            "skillsFrameworks.textGit3",
            "skillsFrameworks.textGit14",
            "skillsFrameworks.textGit5",
            "skillsFrameworks.textGit6",
            "skillsFrameworks.textGit7",
            "skillsFrameworks.textGit8",
        ],
    },
    {
        id: 5,
        title: "skillsFrameworks.titleKnowledge",
        tecnology: "Sass",
        text: [
            "skillsFrameworks.textSass1",
            "skillsFrameworks.textSass2",
            "skillsFrameworks.textSass3",
            "skillsFrameworks.textSass4",
            "skillsFrameworks.textSass5",
        ],
    },
    {
        id: 6,
        title: "skillsFrameworks.titleKnowledge",
        tecnology: "Emotion",
        text: ["skillsFrameworks.textEmotion1", "skillsFrameworks.textEmotion2"],
    },
    {
        id: 7,
        title: "skillsFrameworks.titleFramework",
        tecnology: "Test",
        text: ["Testing-library", "Jest", "Vitest"],
    },
    {
        id: 8,
        title: "skillsFrameworks.titleKnowledge",
        tecnology: "Docker",
        text: [
            "skillsFrameworks.textDocker1",
            "skillsFrameworks.textDocker2",
            "skillsFrameworks.textDocker3",
        ],
    },
];
